name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        
    - name: Test
      run: go test -v ./...
        
    - name: Build
      run: |
        mkdir dist
        go build -o dist/autoshorten -v ./... 
        GOOS=windows GOARCH=amd64 go build -o dist/autoshorten.exe -v ./... 
        GOOS=linux GOARCH=arm go build -o dist/autoshorten.arm -v ./... 
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: ./dist

